/* libglimpse - The Glimpse Library
 * Copyright (C) 1995-2003 Peter Mattis and Spencer Kimball
 *
 * gimp_pdb_headers.h
 *
 * This library is free software: you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.  If not, see
 * <https://www.gnu.org/licenses/>.
 */

/* NOTE: This file is auto-generated by pdbgen.pl */

#if !defined (__GIMP_H_INSIDE__) && !defined (GIMP_COMPILATION)
#error "Only <libglimpse/gimp.h> can be included directly."
#endif

#ifndef __GIMP_PDB_HEADERS_H__
#define __GIMP_PDB_HEADERS_H__

#include <libglimpse/gimp_pdb.h>
#include <libglimpse/gimpbrush_pdb.h>
#include <libglimpse/gimpbrushes_pdb.h>
#include <libglimpse/gimpbrushselect_pdb.h>
#include <libglimpse/gimpbuffer_pdb.h>
#include <libglimpse/gimpchannel_pdb.h>
#include <libglimpse/gimpcolor_pdb.h>
#include <libglimpse/gimpcontext_pdb.h>
#include <libglimpse/gimpdebug_pdb.h>
#include <libglimpse/gimpdisplay_pdb.h>
#include <libglimpse/gimpdrawable_pdb.h>
#include <libglimpse/gimpdrawablecolor_pdb.h>
#include <libglimpse/gimpdrawableedit_pdb.h>
#include <libglimpse/gimpdrawabletransform_pdb.h>
#include <libglimpse/gimpdynamics_pdb.h>
#include <libglimpse/gimpedit_pdb.h>
#include <libglimpse/gimpfileops_pdb.h>
#include <libglimpse/gimpfloatingsel_pdb.h>
#include <libglimpse/gimpfonts_pdb.h>
#include <libglimpse/gimpfontselect_pdb.h>
#include <libglimpse/gimpgimprc_pdb.h>
#include <libglimpse/gimpgradient_pdb.h>
#include <libglimpse/gimpgradients_pdb.h>
#include <libglimpse/gimpgradientselect_pdb.h>
#include <libglimpse/gimphelp_pdb.h>
#include <libglimpse/gimpimage_pdb.h>
#include <libglimpse/gimpimagecolorprofile_pdb.h>
#include <libglimpse/gimpimageconvert_pdb.h>
#include <libglimpse/gimpimagegrid_pdb.h>
#include <libglimpse/gimpimageguides_pdb.h>
#include <libglimpse/gimpimagesamplepoints_pdb.h>
#include <libglimpse/gimpimageselect_pdb.h>
#include <libglimpse/gimpimagetransform_pdb.h>
#include <libglimpse/gimpimageundo_pdb.h>
#include <libglimpse/gimpitem_pdb.h>
#include <libglimpse/gimpitemtransform_pdb.h>
#include <libglimpse/gimplayer_pdb.h>
#include <libglimpse/gimpmessage_pdb.h>
#include <libglimpse/gimppainttools_pdb.h>
#include <libglimpse/gimppalette_pdb.h>
#include <libglimpse/gimppalettes_pdb.h>
#include <libglimpse/gimppaletteselect_pdb.h>
#include <libglimpse/gimppaths_pdb.h>
#include <libglimpse/gimppattern_pdb.h>
#include <libglimpse/gimppatterns_pdb.h>
#include <libglimpse/gimppatternselect_pdb.h>
#include <libglimpse/gimpplugin_pdb.h>
#include <libglimpse/gimpproceduraldb_pdb.h>
#include <libglimpse/gimpprogress_pdb.h>
#include <libglimpse/gimpselection_pdb.h>
#include <libglimpse/gimpselectiontools_pdb.h>
#include <libglimpse/gimptextlayer_pdb.h>
#include <libglimpse/gimptexttool_pdb.h>
#include <libglimpse/gimptransformtools_pdb.h>
#include <libglimpse/gimpunit_pdb.h>
#include <libglimpse/gimpvectors_pdb.h>

#endif /* __GIMP_PDB_HEADERS_H__ */
