/* confdefs.h */
#define PACKAGE_NAME "Glimpse"
#define PACKAGE_TARNAME "glimpse"
#define PACKAGE_VERSION "0.1.0"
#define PACKAGE_STRING "Glimpse 0.1.0"
#define PACKAGE_BUGREPORT "https://github.com/glimpse-editor/Glimpse/issues/new"
#define PACKAGE_URL ""
#define GIMP_PKGCONFIG_VERSION "2.0"
#define GIMP_TOOL_VERSION "2.0"
#define GETTEXT_PACKAGE "gimp20"
#define HAVE_CXX14 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
