name: glimpse-editor
summary: Open Source Image Editor
adopt-info: glimpse
version: git
description: |
  Glimpse is a freely distributed program for such tasks as photo
  retouching, image composition and image authoring.
  It has many capabilities. It can be used as a simple paint
  program, an expert quality photo retouching program, an online
  batch processing system, a mass production image renderer, an
  image format converter, etc.

icon: build-aux/snap/local/glimpse.png
grade: stable
confinement: strict
base: core18

layout:
  /etc/glimpse:
    bind: $SNAP/etc/glimpse
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4
  /usr/lib/glimpse:
    bind: $SNAP/usr/lib/glimpse
  /usr/lib/python2.7:
    bind: $SNAP/usr/lib/python2.7
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs
  /usr/share/color:
    bind: $SNAP/usr/share/color
  /usr/share/ghostscript:
    bind: $SNAP/usr/share/ghostscript
  /usr/share/glimpse:
    bind: $SNAP/usr/share/glimpse
  /usr/share/mypaint-data:
    bind: $SNAP/usr/share/mypaint-data


plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk2-common-themes
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

slots:
  dbus-glimpse:
    interface: dbus
    bus: session
    name: org.glimpse_editor.Glimpse.UI

apps:
  glimpse-editor:
    command: usr/bin/glimpse
    command-chain:
      - snap/command-chain/desktop-launch
      - bin/check-ld-cache
    desktop: usr/share/applications/org.glimpse_editor.Glimpse.desktop
    common-id: org.glimpse_editor.Glimpse
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_EXE_PREFIX: $SNAP/usr
      GIMP2_LOCALEDIR: $SNAP/usr/share/locale
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/usr/lib/python2.7:$SNAP/usr/lib/python2.7/site-packages:$PYTHONPATH
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
      FINAL_BINARY: $SNAP/usr/bin/glimpse
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS

    slots:
      - dbus-glimpse
    plugs:
      - cups-control
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  fix-pkgconfig-files:
    plugin: nil
    override-build: |
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/fix-pkgconfig-files.sh
      for pcfile in \$SNAPCRAFT_PART_INSTALL/usr/lib/\$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/local/lib/\$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/local/lib/pkgconfig/*.pc; do
        sed -i -E "s~^((include|lib)dir=)/usr(/local)?~\1\\\${prefix}~g" \$pcfile || true
        sed -i -E "s~^((exec_)?prefix=)(/usr(/local)?)~\1/\3~" \$pcfile || true
      done
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/fix-pkgconfig-files.sh
    prime:
      - -*

  fix-symlinks:
    # REF: https://unix.stackexchange.com/questions/100918/convert-absolute-symlink-to-relative-symlink-with-simple-linux-command
    plugin: nil
    override-build: |
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
      cd \$SNAPCRAFT_PART_INSTALL
      find . -lname '/*' |
      while read l ; do
        echo ln -sf \$(echo \$(echo \$l | sed 's|/[^/]*|/..|g')\$(readlink \$l) | sed 's/.....//') \$l
      done |
      sh
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
    prime:
      - -*

  gnome-extension:
    after: [patches]
    build-packages:
    - libgail-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    stage-packages:
    - appmenu-gtk2-module
    - gtk2-engines
    - gtk2-engines-pixbuf
    - libatk-adaptor
    - libcanberra-gtk-module
    - libgail-common
    - libgtk2.0-0
    - libgtk2.0-bin
    - unity-gtk2-module
    - ibus-gtk
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: gnome
    override-pull: |
      snapcraftctl pull
      # Remove GTK_PATH setting from launch script...
      # ... we use GTK_EXE_PREFIX instead to support both GTK2 *AND* 3 without conflict
      patch -Np3 < $SNAPCRAFT_STAGE/desktop-launch.patch
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/gtk-2.0
      # Make GTK3 available via GTK_EXE_PREFIX expansion instead of GTK_PATH
      ln -sf ../../gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0 \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-3.0
      # Make GTK2 available via GTK_EXE_PREFIX expansion instead of GTK_PATH
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0 \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0
      ## DISABLED (2 of 4) because gtk2-common-themes only available on amd64
      # Make GTK2 engines available from content snap via GTK_EXE_PREFIX expansion
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0/2.10.0/engines
      ln -sf ../../../../lib/gtk-2.0/2.10.0/engines \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0/2.10.0/

  patches:
    source: build-aux/snap/local/patches
    source-type: local
    plugin: dump
    prime:
      - -*

  scripts:
    source: build-aux/snap/local/scripts
    plugin: dump
    organize:
      build-ld-cache: bin/build-ld-cache
      check-ld-cache: bin/check-ld-cache

  gtk-locales:
    plugin: nil
    build-packages:
      - apt
      - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk20*.mo" -and -not -name "gtk30*.mo" -exec rm '{}' \;
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

  # https://download.gimp.org/pub/babl
  babl:
    after:
      - fix-pkgconfig-files
    plugin: meson
    source: https://download.gimp.org/pub/babl/0.1/babl-0.1.78.tar.xz
    source-checksum: sha256/17d5493633bff5585d9f375bc4df5925157cd1c70ccd7c22a635be75c172523a
    meson-parameters:
      - --prefix=/usr
      - -Dwith-docs=false
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    build-packages:
      - gobject-introspection
      - libgirepository1.0-dev
      - liblcms2-dev
      - librsvg2-bin
      - librsvg2-dev
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -**/*.la

  # https://download.gimp.org/pub/gegl
  gegl:
    after:
      - babl
      - fix-pkgconfig-files
    source: https://download.gimp.org/pub/gegl/0.4/gegl-0.4.22.tar.xz
    source-checksum: sha256/1888ec41dfd19fe28273795c2209efc1a542be742691561816683990dc642c61
    plugin: meson
    meson-parameters:
      - --prefix=/usr
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
      - GIO_MODULE_DIR: $SNAPCRAFT_STAGE/usr/lib/gio/modules
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    build-packages:
      - cmake
      - gobject-introspection
      - graphviz-dev
      - libavcodec-dev
      - libavformat-dev
      - libexiv2-dev
      - libfftw3-dev
      - libgexiv2-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libglu1-mesa-dev
      - libgs-dev
      - libjpeg8-dev
      - libjson-glib-dev
      - liblcms2-dev
      - liblensfun-dev
      - libopenexr-dev
      - libpango1.0-dev
      - libpng-dev
      - libraw-dev
      - librsvg2-dev
      - libsdl1.2-dev
      - libspiro-dev
      - libsuitesparse-dev
      - libswscale-dev
      - libtiff5-dev
      - libv4l-dev
      - libwebp-dev
      - python-gobject-2-dev
      - valac
    stage-packages:
      - graphviz
      - libamd2
      - libavcodec57
      - libavformat57
      - libbtf1
      - libcamd2
      - libccolamd2
      - libcholmod3
      - libcolamd2
      - libcxsparse3
      - libexiv2-14
      - libgexiv2-2
      - libgirepository-1.0-1
      - libglib2.0-0
      - libglu1-mesa
      - libgraphblas1
      - libgs9
      - libjpeg8
      - libjson-glib-1.0-0
      - libklu1
      - liblapack3
      - liblcms2-2
      - libldl2
      - liblensfun1
      - libopenexr22
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpng16-16
      - libraw16
      - librbio2
      - librsvg2-2
      - libsdl1.2debian
      - libspiro0
      - libspqr2
      - libsuitesparseconfig5
      - libswscale4
      - libtiff5
      - libumfpack5
      - libv4l-0
      - libwebp6
      - python-gobject-2
      - python-gi
    stage:
      - -**/*.la
      - -etc
      - -var/lib/ucf
      - -usr/sbin/update-mime
      - -usr/share/X11
      - -usr/share/alsa
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/apps
      - -usr/share/binfmts
      - -usr/share/bug
      - -usr/share/debhelper
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/fonts
      - -usr/share/glib-2.0
      - -usr/share/libdrm
      - -usr/share/libthai
      - -usr/share/lintian
      - -usr/share/locale
      - -usr/share/man
      - -usr/share/menu
      - -usr/share/mime
      - -usr/share/perl5
      - -usr/share/pixmaps
      - -usr/share/pkgconfig
      - -usr/share/python
      - -usr/share/xml
    prime:
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/vala


  # https://github.com/mypaint/libmypaint/releases
  libmypaint:
    after:
      - fix-pkgconfig-files
    plugin: autotools
    source: https://github.com/mypaint/libmypaint/releases/download/v1.5.1/libmypaint-1.5.1.tar.xz
    source-checksum: sha256/aef8150a0c84ce2ff6fb24de8d5ffc564845d006f8bad7ed84ee32ed1dd90c2b
    build-packages:
      - gobject-introspection
      - intltool
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libjson-c-dev
      - libjson-glib-dev
    configflags:
      - --prefix=/usr
      - --disable-static
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    stage:
      - -**/*.la
    prime:
      - -usr/include
      - -usr/lib/pkgconfig

  # https://github.com/mypaint/mypaint-brushes
  mypaint-brushes:
    after:
      - libmypaint
    source: https://github.com/mypaint/mypaint-brushes.git
    source-branch: v1.3.x
    plugin: autotools
    configflags:
      - --prefix=/usr
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe

  # https://github.com/psymole/Glimpse
  glimpse:
    after:
      - gnome-extension
      - babl
      - gegl
      - libmypaint
      - mypaint-brushes
    plugin: autotools
    source: .
    configflags:
    #from glimpse flatpack
      - --disable-docs
      - --disable-gimp-console
      - --disable-gtk-doc
      - --disable-gtk-doc-html
      - --with-icc-directory=/run/host/usr/share/color/icc/
      - --without-webkit
      - --disable-check-update
    #End from glimpse flatpack
      - --prefix=/usr
      - --sysconfdir=/etc
    parse-info: [ usr/share/metainfo/org.glimpse_editor.Glimpse.appdata.xml ]
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
      - BABL_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1
      - GEGL_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4
      - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
      - PYTHON: /usr/bin/python2.7
    override-build: |
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/org.glimpse_editor.Glimpse.png|' desktop/org.glimpse_editor.Glimpse.desktop.in.in
      snapcraftctl build
      sed -i -E 's|^# \(mypaint-brush-path .*$|(mypaint-brush-path "/usr/share/mypaint-data/1.0/brushes:~/.mypaint/brushes")|' $SNAPCRAFT_PART_INSTALL/etc/glimpse/2.0/gimprc
      sed -i -E "s|^(.*python2?=).*|\1/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/bin/python|" $SNAPCRAFT_PART_INSTALL/usr/lib/glimpse/2.0/interpreters/pygimp.interp || true
    build-packages:
      - automake
      - glib-networking
      - gobject-introspection
      - gtk-doc-tools
      - intltool
      - iso-codes
      - libaa1-dev
      - libart-2.0-dev
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libexif-dev
      - libfftw3-dev
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgpm-dev
      - libgtk-3-dev
      - libgtk2.0-dev
      - libgudev-1.0-dev
      - libheif-dev
      - libice-dev
      - libisocodes-dev
      - libjpeg8-dev
      - libmng-dev
      - libopenjp2-7-dev
      - libpoppler-glib-dev
      - libslang2-dev
      - libsm-dev
      - libtiff5-dev
      - try:
        - libunwind-dev # not available in s390x
      - libwebkitgtk-dev
      - libwebp-dev
      - libwmf-dev
      - libx11-dev
      - libxcursor-dev
      - libxmu-dev
      - libxpm-dev
      - libxt-dev
      - zlib1g-dev
      - python-dev
      - python-cairo-dev
      - python-gtk2-dev
      - xsltproc
    stage-packages:
      - ghostscript
      - gir1.2-gtk-2.0
      - gir1.2-poppler-0.18
      - glib-networking
      - gvfs
      - libaa1
      - libart-2.0-2
      - libbz2-1.0
      - libexif12
      - libfftw3-double3
      - libfftw3-single3
      - libgpm2
      - libheif1
      - libmng2
      - libopenjp2-7
      - libpoppler-glib8
      - libslang2
      - libwebkitgtk-1.0-0
      - libwebpdemux2
      - libwebpmux3
      - libwmf0.2-7
      - libxmu6
      - libxpm4
      - libxt6
      - python-cairo
      - python-dev
      - python-gi
      - python-gtk2
      - rawtherapee
      - try:
        - libunwind8 # not available in s390x
        - libfftw3-long3 # only amd64 and i386
        - libfftw3-quad3 # only amd64 and i386
    stage:
      - -**/*.la
      - -etc/dbus-1


  # Ship a default set of GSettings schemas so that the correct theme is used
  # in Wayland sessions on Ubuntu (see https://forum.snapcraft.io/t/7806/3).
  desktop-settings-packages:
    after: [ gnome-extension ]
    plugin: nil
    build-packages:
    - libglib2.0-bin
    stage-packages:
    - gsettings-desktop-schemas
    - ubuntu-settings
    prime:
    - usr/share/glib-2.0/schemas/*

  desktop-settings-build:
    plugin: nil
    after: [ glimpse, desktop-settings-packages ]
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas

  cleanup:
    after: [ glimpse, desktop-settings-build ]
    plugin: nil
    build-snaps:
    - core18
    - gnome-3-28-1804
    - gtk-common-themes
    - gtk2-common-themes
    override-prime: |
      set -eux
      for snap in "core18" "gnome-3-28-1804" "gtk-common-themes" "gtk2-common-themes"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -not -path "$SNAPCRAFT_PRIME/usr/share/gimp/*" -delete
